# name: Cypress Tests
# on: [pull_request]
# env:
#   NEXT_PUBLIC_IPFS_PROVIDER_URI: "https://gateway.pinata.cloud/ipfs/"
# jobs:
#   Component-tests:  
#     name: Run Component Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Cypress run component tests
#         uses: cypress-io/github-action@v4
#         with:
#           working-directory: web
#           component: true
#   E2E-tests:  
#     name: Run E2E Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Cypress run e2e tests
#         uses: cypress-io/github-action@v4
#         with:
#           working-directory: web
#           build: yarn build
#           start: yarn start