name: typescript
on: [pull_request]
jobs:
  Typescript: 
    name: validate-syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run Typescript
        run: yarn workspace web tsc
      - name: Add summary
        run: |
          echo "## Typescript results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY